GCC=gcc

#Bibliotecas
LIB01=lista

#Codigo principal
PROG01=main

#Compila todo
all: cod 

#Compila el codigo principal
cod:
	$(GCC) $(PROG01).cpp $(LIB01).cpp -o $(PROG01) $(LIB01).lib -lstdc++